version: '3'
services:
  frontend:
    build:
      context: ./
      dockerfile: front/Dockerfile
    ports:
      - "5173:5173"
  backend:
    build:
      context: ./
      dockerfile: app/Dockerfile
    ports:
      - "8000:8000"
